version: 2

sources:
  - name: open_live_market
    database: awsdatacatalog
    schema: open_live_market
    tables:
      - name: b2b_product
      - name: b2b_product_cert
      - name: b2b_certificate
      - name: b2b_category
      - name: b2b_product_sku
      - name: b2b_product_sku_price_range
      - name: b2b_brand_profile
      - name: loyalty_brand
      - name: b2b_public_rfq
      - name: b2b_public_rfq_category
      - name: b2b_direct_rfq
      - name: b2b_direct_rfq_detail
      - name: b2b_direct_quote
      - name: b2b_direct_quote_detail
      - name: b2b_quote_to_public_rfq
      - name: b2b_order
      - name: b2b_order_detail
      - name: vinh_test_dbt_cdc
  - name: ob_dwh
    database: awsdatacatalog
    schema: ob_dwh
    tables:
      - name: d_product
      - name: d_b2b_supplier
      - name: fact_action